spring.application.name=EmployeeManagement

spring.datasource.url=jdbc:postgresql://localhost:5433/employee_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#validate,update,create,none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Asia/Kolkata
server.port=8083

logging.level.org.hibernate.type.descriptor.sql=TRACE


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Actuator Health Config
management.endpoint.health.show-details=always